/// Flutter icons Socicons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Socicons
///      fonts:
///       - asset: fonts/Socicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Socicons {
  Socicons._();

  static const _kFontFam = 'Socicons';
  static const _kFontPkg = null;

  static const IconData amplement = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angellist = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appnet = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData endomodo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedburner = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filmweb = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firefox = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grooveshark = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData livejournal = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData periscope = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smugmug = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baidu = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bandcamp = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battlenet = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mixer = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bebee = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bebo = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flattr = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackexchange = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData starcraft = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stayfriends = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steam = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storehouse = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strava = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData streamjar = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swarm = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teamspeak = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teamviewer = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData technorati = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tripadvisor = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tripit = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitch = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uber = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ventrilo = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viadeo = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viber = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viewbug = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vine = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vkontakte = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warcraft = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechat = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weibo = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wikipedia = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windows = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wordpress = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wykop = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yahoo = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yammer = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yandex = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yelp = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData younow = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zapier = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zerply = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zomato = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zynga = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coderwall = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curse = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dailymotion = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deezer = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spreadshirt = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamejolt = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trello = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tunein = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bloglovin = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamewisp = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pandora = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fyuse = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yt_gaming = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sketchfab = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobcrush = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microsoft = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData realtor = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tidal = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qobuz = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData natgeo = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mastodon = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsplash = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeadvisor = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angieslist = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData openaigym = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logmein = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiverr = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guru = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appstore = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homes = IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom = IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alibaba = IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData craigslist = IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wix = IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redfin = IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlecalendar = IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopify = IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freelancer = IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seedrs = IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bing = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doodle = IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bonanza = IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squarespace = IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toptal = IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gust = IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loomly = IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost = IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upwork = IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fundable = IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData booking = IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlemaps = IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zillow = IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData niconico = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toneden = IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crunchbase = IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homefy = IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendly = IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData livemaster = IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData udemy = IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codered = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData origin = IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nextdoor = IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portfolio = IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hackernews = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smashwords = IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kobo = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookbub = IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mailru = IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moddb = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indiedb = IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData traxsource = IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamefor = IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pixiv = IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myanimelist = IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blackberry = IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wickr = IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spip = IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData napster = IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beatport = IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hackerone = IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internet = IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invision = IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torial = IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collectorz = IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seenthis = IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googleplaymusic = IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData debian = IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filmfreeway = IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gnome = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itchio = IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jamendo = IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mix = IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData threema = IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData splice = IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData metapop = IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData naver = IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remote = IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flipboard = IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData googlehangouts = IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dlive = IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vsco = IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stitcher = IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avvo = IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
